# Generated by Django 6.0.4 on 2026-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_order_customer_fields_guest_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(default="+212", max_length=30),
            preserve_default=False,
        ),
    ]
